### ISSUE TITLE
DigitalOut API is confusing

### ISSUE THREAD

**Issue by kylestach** [RoboJackets/mtrain-firmware#38]
Specifically, the overloaded `operator=` for writing makes for code that is very difficult to read. I would prefer it just gets deleted so we can use `.write()` on the firmware side.

https://github.com/RoboJackets/mtrain-firmware/blob/master/API/cpp/Inc/DigitalOut.hpp

**Comment by Arvind-Srinivasan** [comment]
@guyfleeman you intended to have the operator overloaded right?

**Comment by matthewawhite** [comment]
We wanted overload the operator because we wanted to make it similar to how mbed does DigitalOut. Once you get used to the assignment operator it actually saves some time since you can do things like:
output pin = input pin;

It just makes it so you don’t need read and write statements, which in my opinion is easy and quick to read once you get used to it.

**Comment by Arvind-Srinivasan** [comment]
Personally, I'm with @kylestach, just because its shorter code doesn't make it better code.

**Comment by matthewawhite** [comment]
It really just comes down what you’re used to, for most ECE majors it’s normal since we all used mbeds but I guess CS majors don’t have exposure to it. We might as well get of it though since we’re starting to have more CS majors write firmware.

**Comment by kylestach** [comment]
Code is meant to be read, not written. Readability should take precedence over brevity when the two are in conflict. 

Using that as a guiding principle becomes increasingly important as projects get larger. For small embedded projects, maybe that makes sense. But with the planned increase in firmware complexity, I just don't think it's going to fly.

**Comment by matthewawhite** [comment]
I agree with making code readable, but as I was saying it depends on what you’re used to. For people who use mbed overloading the operator is just as readable as having a write call, but since we have more people not used to mbed firmware I’m fine with getting rid of the operator.

**Comment by guyfleeman** [comment]
Yeah that overload went back to the days when we were targeting source level compatibility with mbed-os. I think we should change it

**Comment by Arvind-Srinivasan** [comment]
The thing is, not everyone from ECE has used a mbed. When I wrote this, I never had actually used a mbed.

**Comment by kylestach** [comment]
That's fair. I wasn't aware that it was a convention used in mbed. I still think it should be removed, though.

**Comment by matthewawhite** [comment]
Ya, it’s a legacy thing for us now since it used to be that all firmware people understood mbed syntax since we were using the mbed instead of mtrain, that’s why I think we should get rid of it since that doesn’t hold true anymore
